drop table airplane if exists;
drop table airplane_cost_estimates_list if exists;
drop table car if exists;
drop table car_cost_estimates_list if exists;
drop table cost_estimates if exists;

create table airplane (
    id bigint generated by default as identity,
    brand varchar(255),
    model varchar(255),
    year_of_issue integer,
    fuel_capacity integer,
    manufacturer varchar(255),
    seats integer,
    primary key (id));

create table airplane_cost_estimates_list (
    airplane_id bigint not null,
    cost_estimates_list_id bigint not null);

create table car (
    id bigint generated by default as identity,
    brand varchar(255),
     model varchar(255),
      year_of_issue integer,
      power double,
      primary key (id));

create table car_cost_estimates_list (
    car_id bigint not null,
    cost_estimates_list_id bigint not null);

create table cost_estimates (
    id bigint not null,
    estimates_value decimal(19,2),
    estimates_date date,
    primary key (id));

alter table airplane_cost_estimates_list
    add constraint UK_AIRPLANE_COST_ESTIMATES_LIST_ID
        unique (cost_estimates_list_id);

alter table car_cost_estimates_list
    add constraint UK_CAR_COST_ESTIMATES_LIST_ID
        unique (cost_estimates_list_id);

alter table airplane_cost_estimates_list
    add constraint FK_AIRPLANE_COST_ESTIMATES_LIST_ID
        foreign key (cost_estimates_list_id)
            references cost_estimates;

alter table airplane_cost_estimates_list
    add constraint FK_AIRPLANE_ID
        foreign key (airplane_id)
            references airplane;

alter table car_cost_estimates_list
    add constraint FK_CAR_COST_ESTIMATES_LIST_ID
        foreign key (cost_estimates_list_id)
            references cost_estimates;

alter table car_cost_estimates_list
    add constraint FK_CAR_ID
        foreign key (car_id) references car;